### ISSUE TITLE
[css] 개선하기

### ISSUE THREAD

**Issue by moon9ua** [lolchess/loltoGG#14]
* [x] loltoGG 로고 넣기
* [x] 전체 글씨체 수정하기 - 수정했으나... 수정이 된건가? 윈도우에서 확인 필요
* [x] 네비게이션 눈누 스타일로 고쳐보기
* [x] ~네비게이션 focus시 효과 주기~ 중요해서 따로 이슈로 분리하도록 하겠습니다.
* [x] 찾기에서 엔터 눌러도 작동하도록 개선 (css는 아닌데... 그냥 일단 여기에 써봄...)

**Comment by seohee-choi** [comment]
- [x] community 게시글 css 적용하기

**Comment by moon9ua** [comment]
완료됐으니 이슈 닫겠습니다!
